name: todo_app_learning
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # Service locator
  get_it: ^3.1.0
  # Bloc for state management
  flutter_bloc: ^3.2.0
  # Value equality
  equatable: ^1.1.0
  # Functional programming thingies
  dartz: ^0.8.9
  # Freezed Package for Union
  freezed_annotation: ^0.7.1
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+4
  # Local cache
  shared_preferences: ^0.5.6+1
  # Firebase Dependencies
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.15.5+2
  google_sign_in: ^4.1.4
  firebase_core: ^0.4.4+2
  cloud_firestore: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mockito: ^4.1.1
  freezed: ^0.10.1

flutter:
  uses-material-design: true
